name: _file_anchor_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/file_anchor_platform_interface
  - packages/file_anchor
  - packages/file_anchor_android
  - packages/file_anchor_android/example
