name: _file_anchor_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/file_anchor_platform_interface
  - packages/file_anchor
  - packages/file_anchor_path_io
  - packages/file_anchor_android
  - packages/file_anchor_ios
  - packages/file_anchor_linux
  - packages/file_anchor_macos
  - packages/file_anchor_windows
  - example

dev_dependencies:
  flutter_lints: ^6.0.0
